/*

  Arkanon <arkanon@lsd.org.br>
  2015/11/25 (Qua) 13:10:35 BRS
  2015/11/25 (Wed) 00:58:23 BRS
  2015/11/20 (Sex) 08:19:29 BRD
  2015/11/16 (Seg) 18:03:14 BRD
  2015/11/14 (Sat) 00:24:15 BRS
  2015/11/13 (Fri) 15:34:59 BRD

  Inicia o processo
    >| nohup.out
    nohup maxima --very-quiet --batch=04-avaliacao_de_pontos.mac &
    cat nohup.out

  Finaliza o processo
    killall -SIGINT maxima

  Acompanha a iteração editando o log no VIm. Executar no vim o comando ex
    :set autoread

  Carrega os aliases bash de acompanhamento do log e da convergência
    . aliases.sh

  Acompanha a iteração
    log0
    log

  Acompanha a convergência
    ./times.sh
    ./conv.sh
    conv

  Compara a precisão da geração com menos dígitos com a precisão da geração de 500 dígitos
    ./compare.sh 04-avaliacao_de_pontos-050dig-40000-10000-00050.log 7

*/

  load("ambiente.mac")$

  x:1/%e^%e;

  fpprec:50;

  f(n,x,y) := block
  (
    [ i:1 ],
    if x=0 then if remainder(n,2)=0 then 1 else 0 else
    (
      for i:1 thru n do y : x^y,
      y
    )
  )$

  git:sconcat( HOME , "/git/f" )$

/*                   */   k0 : 44721$
/*                   */ t_k0 : 1018617.8$
/* f_k0 : <value>b0$ */ f_k0 : 0.36788546735236691349401429205241966668191445114004b0$

/*   k1 : 1+k0$      */   k1 : 1+k0$ /* def: k1:1 */
/*                   */   ti : t_k0$ /* def: ti:0 */
/*   fi : f_k0$      */   fi : f_k0$ /* def: fi:1 */

/*
  nk:2000*10000*50$
  nj:1$
  ni:1$
*/

  nk:100000$
  nj:10000$
  ni:50$

  file:sconcat( git, "/04-avaliacao_de_pontos-", numpad(fpprec,3,"0",0,""), "dig-", numpad(nk,6,"0",0,""), "-", numpad(nj,6,"0",0,""), "-", numpad(ni,6,"0",0,""), ".log" )$

  header:""$
  if not file_search(file) then header:"-----𝑘|--𝑛=𝑘·𝑛ⱼ·𝑛ᵢ|-----tⱼᵢ------|--------tₜₒₜₐₗ---------|------data e hora (utc)-------|ƒₙ(1/𝑒ᵉ) → 1/𝑒 ≈ 0.36787944117144~%"$

  out:opena( file )$

  t0:ts()$
  t0[4];
  printf( out, sconcat(header,"~%------|-----------|------|-------|---------|-------------|~d|~a|~%"), t0[3], t0[4] )$

  for k:k1 thru nk do
  (
    t1:ts(),
    for j:1 thru nj do fi:bfloat(f(ni,x,fi)),
    t2:ts(),
    printf
    (
      out,
      "~a|~a|~a|~a|~a|~a|~d|~a|~h~%",
      numpad  ( k             ,  6," ", 0,""  ),
      numpad  ( k*nj*ni       , 11," ", 0,""  ),
      numpad  ( t2[1]-t1[1]   ,  4," ", 1,"0" ),
      sf2msf  ( t2[1]-t1[1]   ,  1            ),
      numpad  ( t2[1]-t0[1]+ti,  7," ", 1,"0" ),
      sf2dhmsf( t2[1]-t0[1]+ti,  1            ),
      t2[3],
      t2[4],
      fi
    )
  )$
  sf2dhmsf(time(%)[1],1);
  t2[4];

  close(out)$

  printf(true,"~h",fi)$

/* EOF */
